# Generated by Django 5.2.4 on 2025-07-12 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_id', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos_mascotas/')),
                ('vacunado_rabia', models.BooleanField(default=False)),
                ('nombre_dueno', models.CharField(max_length=100)),
                ('telefono_dueno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
