# Generated by Django 5.2.4 on 2025-07-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='email_dueno',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del dueño'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='rut_dueno',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RUT del dueño'),
        ),
    ]
